# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 707cc82711ef5c53ebdb7aa6f4b305dd9e6e0d30dce16685b851b929b391dc44520687080711c50f083c39ecea387a8e79ceb07e8227c4a558a720154b8beae2

test:
  secret_key_base: 354db333c7995244ce2b9aa048162eeeb5d473c8deafede1620bad0d27107e65e1c6bd84023bbdbd58fe72c5ad2a5eb2b4310221c412c8416ca9ff628c3ed204

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
